apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrd.abhay.com
spec:
  group: abhay.com
  names:
    plural: mycrds
    singular: mycrd
    kind: mycrd
    shortNames:
    - myc
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          appId:
            type: string
          language: 
            type: string
            enum:
            - csharp
            - python
            - go
          os: 
            type: string
            enum:
            - windows
            - linux
            - macos
          instancetype:
            type: string
            enum:
            - small
            - medium
            - large
          environmentType:
            type: string
            enum:
            - dev
            - test
            - prod
          replicas:
            type: string
            minimum: 1
        required: ["appId", "language", "environmentType"]
      required: ["spec"]
          